 create sequence hibernate_sequence start 1 increment 1;
 create table bucket (id int8 not null, user_id int8, primary key (id));
 create table buckets_products (bucket_id int8 not null, product_id int8 not null);
 create table message (id int8 not null, filename varchar(255), text varchar(2000), user_id int8, product_id int8, primary key (id));
 create table order_details (id int8 not null, amount numeric(19, 2), price numeric(19, 2), order_id int8, product_id int8, primary key (id));
 create table orders (id int8 not null, address varchar(255), created timestamp, status varchar(255), sum numeric(19, 2), updated timestamp, user_id int8, primary key (id));
 create table orders_details (order_id int8 not null, details_id int8 not null);
 create table product_product_images (product_id int8 not null, product_images varchar(255));
 create table products (type varchar(31) not null, id int8 not null, price numeric(19, 2), title varchar(255), year int4, author varchar(255), book_title varchar(255), brand varchar(255), screen_size int4, primary key (id));
 create table user_role (user_id int8 not null, roles varchar(255));
 create table users (id int8 not null, activation_code varchar(255), active boolean not null, email varchar(255), password varchar(255), username varchar(255), bucket_id int8, primary key (id));
 alter table if exists orders_details add constraint UK_kk6y3pyhjt6kajomtjbhsoajo unique (details_id);
 alter table if exists bucket add constraint FK327w43qqj7sg7250igsyxw7s3 foreign key (user_id) references users;
 alter table if exists buckets_products add constraint FKloyxdc1uy11tayedf3dpu9lci foreign key (product_id) references products;
 alter table if exists buckets_products add constraint FKirwnurgj5ecdsln467r5vtr7i foreign key (bucket_id) references bucket;
 alter table if exists message add constraint FKpdrb79dg3bgym7pydlf9k3p1n foreign key (user_id) references users;
 alter table if exists message add constraint FKl9frkkfcf313fm8wk5iq4gj63 foreign key (product_id) references products on DELETE CASCADE;
 alter table if exists order_details add constraint FKjyu2qbqt8gnvno9oe9j2s2ldk foreign key (order_id) references orders;
 alter table if exists order_details add constraint FK4q98utpd73imf4yhttm3w0eax foreign key (product_id) references products;
 alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
 alter table if exists orders_details add constraint FKbblrq2kcscnyr9fsv8ptp98wy foreign key (details_id) references order_details;
 alter table if exists orders_details add constraint FK5o977kj2vptwo70fu7w7so9fe foreign key (order_id) references orders;
 alter table if exists product_product_images add constraint FKsarw66pof8as6lj9rklndlq3u foreign key (product_id) references products on delete  cascade;
 alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
 alter table if exists users add constraint FKjrj2n57abkxvdjr5jiwfm0tmj foreign key (bucket_id) references bucket;